site_name: Tenguesta Ngoldorinwa v0.2
site_url: https://feophan.github.io/tenguesta_ngoldorinwa/

nav:
    - 'Morphology':
        - '4. Nouns': morph/nou.md
        - '12. Introduction to Verb Forms': morph/ivf.md
        - '13. The Aorist': morph/vfa.md
    - 'Syntax':
        - '26. Simple Sentences': syntx/sen.md
        - '27. Agreement': syntx/agr.md
        - '28. The Article': syntx/art.md
        - '29. Pronouns and Quantifiers': syntx/pro.md
        - '30. Cases': syntx/cas.md
    - 'Appendix':
        - 'Article': dat/art.md
            
theme:
    name: readthedocs
    navigation_depth: 2
        
markdown_extensions:
  - footnotes
  - admonition
  - abbr
  - mdx_custom_span_class
  - mdx_emdash
  - attr_list

extra_javascript:
  - js/extra.js

extra_css:
  - stylesheets/extra.css
  - https://use.fontawesome.com/releases/v5.12.0/css/all.css
