site_name: Tenguesta Goldorinwa
site_url: https://feophan.github.io/tenguesta_ngoldorinwa/

nav:
    - 'Phonology':
        - '1. The Sounds': phon/sou.md
        - '1a. Accentuation': phon/acc.md
        - '2. The Signs': phon/sig.md
    - 'Morphology':
        - '3. The Article': morph/art.md
        - '4. Nouns': morph/nou.md
        - '5. Adjectives and Participles': morph/aap.md
        - '6. Adverbs': morph/adv.md
        - '12. Introduction to Verb Forms': morph/ivf.md
        - '13. The Aorist': morph/vfa.md
        - '14. The Present': morph/vfi.md
        - '15. The Perfect': morph/vfp.md
        - '16. Principal Parts': morph/vov.md
    - 'Syntax':
        - '26. Simple Sentences': syntx/sen.md
        - '27. Agreement': syntx/agr.md
        - '28. The Article': syntx/art.md
        - '29. Pronouns and Quantifiers': syntx/pro.md
        - '30. Cases': syntx/cas.md
        - '32. Comparison': syntx/cmp.md
        - '33. The Verb: Tense and Aspect': syntx/taa.md
    - 'Appendix':
        - 'Definite Article': app/art.md
        - 'Aspect': app/taa.md
            
theme:
    name: readthedocs
    navigation_depth: 4
        
markdown_extensions:
  - footnotes
  - admonition
  - abbr
  - mdx_custom_span_class
  - mdx_emdash
  - attr_list
  - pymdownx.details

extra_javascript:
  - js/extra.js

extra_css:
  - stylesheets/extra.css
  - https://use.fontawesome.com/releases/v5.12.0/css/all.css
